name: 'Params for tests'
description: 'Runs tests with params'
inputs:
  testPage:
    description: 'url of page under test'
    required: true
  prodPage:
    description: 'url of prod page'
    required: true
outputs:
  results:
    description: 'returns the failed tests'
runs:
  using: node16
  main: 'index.js'
