name: 'Params for tests'
description: 'Runs tests with params'
inputs:
  testPage:
    description: 'url of page under test'
    required: true
  prodPage:
    description: 'url of prod page'
    required: true
  ticket:
    description: 'jira ticket number'
    required: false
outputs:
  results:
    description: 'returns the failed tests'
  passed:
    description: 'pass fail of all tests'
runs:
  using: node16
  main: 'src/index.js'
