### Trigger the github workflow with params
POST https://api.github.com/repos/PeakActivity/renuity-qa/dispatches
Accept: application/vnd.github.everest-preview+json
Content-Type: application/json
Authorization: Bearer {{github_token}}

{
  "event_type": "on-demand-test",
  "client_payload": {
    "testPage": "https://statewidemodev.wpengine.com/blog/5-decor-ideas-to-create-a-spa-like-bathroom-on-a-budget",
    "prodPage": "https://www.statewideremodeling.com/blog/p.201116000/5-decor-ideas-to-create-a-spa-like-bathroom-on-a-budget",
    "ticket": "REN-804"
  }
}

### GET JIRA Issue
GET https://peakactivity.atlassian.net/rest/api/2/issue/REN-1367
Accept: application/json
Authorization: Basic {{jira_username}} {{jira_token}}
