### Trigger the github workflow with params
POST https://api.github.com/repos/PeakActivity/renuity-qa/dispatches
Accept: application/vnd.github.everest-preview+json
Content-Type: application/json
Authorization: Bearer {{github_token}}

{
  "event_type": "on-demand-test",
  "client_payload": {
    "testPage": "https://statewidemodev.wpengine.com/blog/bathroom-lighting-ideas-to-create-a-dreamy-atmosphere",
    "prodPage": "https://www.statewideremodeling.com/blog/p.201228000/bathroom-lighting-ideas-to-create-a-dreamy-atmosphere",
    "ticket": "REN-809"
  }
}

### GET JIRA PROJECTS
GET https://peakactivity.atlassian.net/rest/api/3/project
Accept: application/json
Authorization: Basic {{jira_username}} {{jira_token}}

