

### Trigger the official way
POST https://api.github.com/repos/PeakActivity/renuity-qa/dispatches
Accept: application/vnd.github.everest-preview+json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "event_type": "on-demand-test",
  "client_payload": {
    "testPage": "https://statewidemodev.wpengine.com/blog/bathroom-lighting-ideas-to-create-a-dreamy-atmosphere",
    "prodPage": "https://www.statewideremodeling.com/blog/p.201228000/bathroom-lighting-ideas-to-create-a-dreamy-atmosphere",
    "ticket": "REN-809"
  }
}
